import Head from "next/head";
import Layout from "./Layout";
import 'react-toastify/dist/ReactToastify.css';
import Dashboard from "@/components/Dashboard/Dashboard";
import { useEffect, useState } from "react";

export default function Home() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    const user = localStorage.getItem('user') ? JSON.parse(localStorage.getItem('user')) : null;
    setUser(user);
  }, [])

  return (
    <Layout>
      <Head>
        <title> Home </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard user={user} />
    </Layout>
  )
}